// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape an [`AppError`] takes when it crosses IPC.
 */
export type AppErrorPayload = { 
/**
 * Stable discriminant, e.g. `"grib"`.
 */
kind: string, 
/**
 * Human-readable message. Not intended for programmatic branching.
 */
message: string, };
