// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shortcut } from "./Shortcut";

/**
 * The application's persisted preferences.
 */
export type AppSettings = { 
/**
 * Every binding, in the order the dialog lists them.
 */
shortcuts: Array<Shortcut>, 
/**
 * The colour-ramp top a *new* wind project gets, in knots.
 */
default_wind_scale_knots: number, 
/**
 * And a new current project.
 */
default_current_scale_knots: number, 
/**
 * Where the macro library lives. Empty means the default under the app
 * data directory (M16).
 */
macro_directory: string, };
