// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the autosave thread does with a dirty project (D70, M25).
 */
export type AutosaveMode = "off" | "recovery" | "save";
