// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the brush decides each cell's direction (spec.md 6.2).
 */
export type BrushDirectionMode = "constant" | "toward_point" | "away_from_point";
