// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of a capture the session is in (spec.md 8.7, M26).
 */
export type CapturePhase = "recording" | "previewing";
