// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preferred display unit for ground distances; stored geometry remains km.
 */
export type DistanceUnit = "km" | "nm";
