// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which field evaluator backend is active, and why.
 */
export type EvaluatorSelection = { 
/**
 * Backend name, e.g. `"wgpu"` or `"cpu"`.
 */
backend: string, 
/**
 * Why the GPU backend was not used, if it was not. `None` when GPU is active.
 */
fallback_reason: string | null, };
