// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress, emitted as the `export://progress` event.
 *
 * `Deserialize` as well as `Serialize`: `mcp::tools`'s progress relay reads
 * the event back off the bus to forward it to an MCP client.
 */
export type ExportProgress = { 
/**
 * Steps completed.
 */
step: number, 
/**
 * Steps in total.
 */
total: number, 
/**
 * Bytes written so far.
 */
bytes: bigint, };
