// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to export and where for a Zarr V3 export.
 */
export type ExportZarrRequest = { 
/**
 * Destination directory (normally ending in `.zarr`).
 */
path: string, 
/**
 * Forecast reference year.
 */
year: number, 
/**
 * Month, 1-12.
 */
month: number, 
/**
 * Day, 1-31.
 */
day: number, 
/**
 * Hour, 0-23.
 */
hour: number, };
