// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an export produced.
 */
export type ExportResult = { 
/**
 * Where it was written.
 */
path: string, 
/**
 * Total bytes.
 */
bytes: bigint, 
/**
 * Messages written: two per time step.
 */
messages: number, 
/**
 * How long it took, in milliseconds.
 */
elapsed_ms: bigint, };
