// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An estimate shown before the user commits to an export.
 */
export type ExportEstimate = { 
/**
 * Approximate output size in bytes.
 */
bytes: bigint, 
/**
 * Messages that will be written.
 */
messages: number, 
/**
 * Grid points per message.
 */
points_per_message: bigint, };
