// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionDependency } from "./OptionDependency";

/**
 * The eyedropper a tool offers, on the wire (spec.md 6.1).
 *
 * Two property names and the conditions that make them meaningful. The bar
 * renders a button from this and nothing else, so a tool gains an eyedropper
 * by declaring one in the schema.
 */
export type EyedropperSpec = { 
/**
 * The speed option it writes, in m/s.
 */
speed: string, 
/**
 * The direction option it writes, as an azimuth-toward.
 */
direction: string, 
/**
 * What makes it inert, in the same terms an option's dependencies use.
 */
depends_on: Array<OptionDependency>, };
