// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the panel and the map need to know about a GIS layer (spec.md 4.11).
 */
export type GisLayerView = { 
/**
 * The layer this belongs to.
 */
layer: bigint, 
/**
 * The file, as the user chose it.
 */
path: string, 
/**
 * Line and point colour, `#rrggbb`.
 */
colour: string, 
/**
 * Line width in screen pixels.
 */
width_px: number, 
/**
 * How strongly areas are filled, `0.0` to `1.0`.
 */
fill_opacity: number, 
/**
 * Whether the file could be read. False leaves the layer present and
 * empty, exactly as a missing GRIB does.
 */
loaded: boolean, 
/**
 * How many features it holds.
 */
features: number, 
/**
 * What it covers: west, south, east, north. Absent when unread.
 */
bounds: Array<number> | null, 
/**
 * Why it could not be read, where it could not.
 */
error: string | null, };
