// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One atomic appearance edit; simultaneous controls cannot overwrite each other.
 */
export type GlyphSetting = { "property": "size_percent", "value": number } | { "property": "stroke_width_px", "value": number } | { "property": "color", "value": string } | { "property": "opacity_percent", "value": number } | { "property": "density_percent", "value": number } | { "property": "fade_with_speed", "value": boolean } | { "property": "shadow_enabled", "value": boolean } | { "property": "shadow_color", "value": string } | { "property": "shadow_opacity_percent", "value": number } | { "property": "shadow_offset_x_px", "value": number } | { "property": "shadow_offset_y_px", "value": number } | { "property": "reset" };
