// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One gradient on the wire.
 */
export type GradientView = { 
/**
 * What the document stores, e.g. `"viridis"`.
 */
id: string, 
/**
 * What the settings offer.
 */
label: string, 
/**
 * A sentence on what it is for.
 */
note: string, 
/**
 * Stops as `0.0`–`1.0` RGB, calm first, evenly spaced across the range.
 */
stops: Array<[number, number, number]>, };
