// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the panel says about a layer's imported field (spec.md 4.8).
 */
export type GribLayerInfo = { 
/**
 * The file the field is read from.
 */
path: string, 
/**
 * `"wind"` or `"current"`.
 */
field_kind: string, 
/**
 * Whether the file was read; false when it is missing or unreadable,
 * in which case the layer contributes nothing.
 */
loaded: boolean, 
/**
 * Time slices the file holds, or 0 when not loaded.
 */
frame_count: number, 
/**
 * Hours from the first slice to the last, or 0 when not loaded.
 */
span_hours: number, 
/**
 * The band of speeds the layer keeps, in m/s, if it filters (spec.md 4.8).
 */
speed_min_mps: number | null, 
/**
 * The top of that band.
 */
speed_max_mps: number | null, 
/**
 * The fastest speed the file holds, in m/s, over every message.
 *
 * What the panel's slider runs to: a filter is set by looking at the
 * field, and a scale that ended at a number the file never reaches would
 * spend most of its travel on nothing.
 */
speed_ceiling_mps: number, 
/**
 * Which of the project's steps the file has a message for.
 *
 * One entry per step, in step order. A step the file says nothing about
 * shows no imported field at all (spec.md 4.8), and a timeline that did
 * not say which those were would leave the user to work it out from a
 * field that comes and goes. The timeline marks them.
 */
covered_steps: Array<boolean>, };
