// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryWork = { phase: string,
/**
 * Estimated overall completion, from 0 to 1; never moves backwards.
 */
fraction: number, downloaded_bytes: bigint, };
