// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far along a fetch is, emitted as the `history://progress` event.
 *
 * A history import is minutes of silence otherwise, and an indeterminate
 * spinner cannot tell a slow fetch from a stalled one. The steps are known
 * before the first byte moves, so the bar is a real fraction rather than an
 * animation.
 */
export type HistoryProgress = { 
/**
 * Which archive is being read, as [`Archive::label`] names it.
 */
archive: string, 
/**
 * Steps fetched so far, across every archive of this import.
 */
done: number, 
/**
 * Steps this import will fetch in total, across every archive.
 */
total: number, };
