// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryArchive } from "./HistoryArchive";

/**
 * What one archive offers, for a caller choosing what to ask for.
 *
 * The interface names the archives in its own panel; a client of the MCP
 * service has only this. The coverage is the point: the archives trail the
 * present by days to months, and a range past the end is refused only after
 * the client has built a project around it.
 */
export type HistoryArchives = {
/**
 * The present moment, ISO 8601 UTC. A client asked for "the last" of
 * something has to count back from here, and a model's own sense of
 * the date is its training's, not the clock's.
 */
now: string,
/**
 * What can be downloaded.
 */
archives: Array<HistoryArchive>, };
