// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the undo history.
 */
export type HistoryEntry = { 
/**
 * Position in the stack, oldest first.
 */
index: number, 
/**
 * What the change was.
 */
label: string, 
/**
 * Whether it is currently applied.
 */
applied: boolean, };
