// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend gets when it asks about an image layer.
 */
export type ImageLayerView = { 
/**
 * Which layer this is.
 */
layer: bigint, 
/**
 * The file, for the panel to show and for a missing-file message.
 */
path: string, 
/**
 * Whether the file could be read at all.
 */
loaded: boolean, 
/**
 * The image's size in its own pixels, before any downsampling.
 */
width: number, 
/**
 * And its height.
 */
height: number, 
/**
 * Where it sits: `[a, b, c, d, e, f]` (see `Placement`).
 */
placement: [number, number, number, number, number, number], 
/**
 * How strongly it shows, 0 to 1.
 */
opacity: number, 
/**
 * The pairs that warp it: `[u, v, lon, lat]` each.
 */
control_points: Array<[number, number, number, number]>, 
/**
 * Whether those pairs bend the picture, so the map must draw it
 * through the mesh rather than the globe's per-pixel inverse
 * (spec.md §4.9). False for an image with no pairs, or with pairs
 * that happen to fit an affine.
 */
warped: boolean, 
/**
 * The warp sampled on a `(warp_cells + 1)` by `(warp_cells + 1)` grid,
 * lon/lat interleaved and flattened — `[lon0, lat0, lon1, lat1, ...]` —
 * because it becomes a `Float32Array` in a vertex buffer. Empty when
 * `warped` is false: an unwarped image needs no mesh.
 */
warp_mesh: Array<number>, 
/**
 * The cell count `warp_mesh` was evaluated at. Zero when `warped` is
 * false.
 */
warp_cells: number, 
/**
 * The image's four corners as `[lon, lat]`, top-left first, clockwise.
 *
 * Taken from the warp at image pixels (0,0), (w,0), (w,h), (0,h), so it
 * is the *bent* quad for a warped image and the plain one otherwise. The
 * map hit-tests against this; it is not what the picture is drawn from.
 */
corners: Array<[number, number]>, 
/**
 * Whether the file carried its own georeference.
 *
 * A hand-placed image says so, because "the corners are where the file
 * said" and "the corners are where you dragged them" are very different
 * claims about an overlay someone is about to trace.
 */
georeferenced: boolean, };
