// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GribLayerInfo } from "./GribLayerInfo";
import type { ImageLayerView } from "./ImageLayerView";
import type { ObjectNode } from "./ObjectNode";

/**
 * One layer, with its objects in z-order.
 */
export type LayerNode = { 
/**
 * Stable identity.
 */
id: bigint, 
/**
 * User-editable name.
 */
name: string, 
/**
 * Whether the layer contributes and is drawn.
 */
visible: boolean, 
/**
 * Whether its objects can be selected and edited.
 */
locked: boolean, 
/**
 * Objects, bottom of the layer first.
 */
objects: Array<ObjectNode>, 
/**
 * The imported field beneath the objects, for a GRIB layer.
 */
grib: GribLayerInfo | null, 
/**
 * The picture beneath everything, for an image layer (spec.md 4.9, M18).
 */
image: ImageLayerView | null, 
/**
 * What the layer is (M29): `"painted"`, `"raster"` for an imported GRIB,
 * `"image"` for a picture. Says which controls the panel offers.
 */
source: string, 
/**
 * Which field the layer is part of — `"wind"` or `"current"`: its
 * file's for a raster layer, none that matters for an image (M29).
 */
parameter: string, };
