// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the library, as the panels list it.
 */
export type MacroEntry = { 
/**
 * The file's stem, which is also how it is addressed.
 */
id: string, 
/**
 * The name the user gave it.
 */
name: string, 
/**
 * `"wind"` or `"current"`, from the project it was taken in.
 */
field_kind: string, 
/**
 * How many time slices it holds.
 */
frames: number, 
/**
 * Hours from its first frame to its last.
 */
span_hours: number, 
/**
 * The step size it was captured at, in hours.
 */
step_hours: number, 
/**
 * Bytes on disk.
 */
size_bytes: bigint, 
/**
 * Whether any frame's region moved: a macro that records movement.
 */
moves: boolean, };
