// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which MCP tools a client may run without asking (spec.md 8.8), by their
 * effect (`mcp::tools::effects`).
 */
export type McpAsk = "outside" | "everything" | "nothing";
