// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A client the Settings dialog can register the service with.
 */
export type McpClient = "claude_code" | "codex";
