// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAsk } from "./McpAsk";

/**
 * The MCP service's switch, port and token (spec.md 8.8).
 *
 * The token is a plain string in the file the person already owns: it
 * grants a local process what sitting at the keyboard grants, nothing more.
 * Empty means no token, and `token::matches` refuses everything then.
 */
export type McpSettings = { enabled: boolean, port: number, token: string, 
/**
 * What a client may do without asking the person first. Applied when an
 * Add button is pressed (`mcp::clients`), not when it changes.
 */
ask: McpAsk, 
/**
 * The Claude Code permission rules the last *Add to Claude Code* wrote,
 * so the next one replaces exactly those and never a rule the person
 * wrote themselves (`mcp::claude_settings`).
 */
claude_rules: Array<string>, };
