// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Settings dialog shows about the service (spec.md 8.8).
 */
export type McpStatus = { enabled: boolean, port: number, 
/**
 * The token, so the dialog can build a client configuration.
 */
token: string, 
/**
 * The port actually bound, or null while off or if binding failed.
 */
bound_port: number | null, 
/**
 * Why the listener is not up although the setting is on.
 */
bind_error: string | null, 
/**
 * Open client sessions.
 */
sessions: number, 
/**
 * The last tool a client called, if any.
 */
last_tool: string | null, };
