// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The MCP service's switch, port and token (spec.md 8.8).
 *
 * The token is a plain string in the file the person already owns: it
 * grants a local process what sitting at the keyboard grants, nothing more.
 * Empty means no token, and `token::matches` refuses everything then.
 */
export type McpSettings = { enabled: boolean, port: number, token: string, };
