// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredPathView } from "./MeasuredPathView";
import type { MeasurementKind } from "./MeasurementKind";

/**
 * A measurement, as the map draws it.
 */
export type MeasurementView = { 
/**
 * Which measurement this is, for dragging and clearing.
 */
id: bigint, 
/**
 * Which tool made it.
 */
kind: MeasurementKind, 
/**
 * The points the user placed, as `[lon, lat]`. These are the handles.
 */
handles: Array<[number, number]>, 
/**
 * The lines to draw, in order.
 */
paths: Array<MeasuredPathView>, 
/**
 * The chain's total, for a measurement that has one.
 */
total: string | null, 
/**
 * Where the total belongs: at the last point placed.
 */
total_at: [number, number] | null, };
