// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tool made a measurement (spec.md 10).
 *
 * A mirror of [`annotation::MeasurementKind`], for the same reason
 * [`crate::edit::StampSpace`] mirrors its schema constant: `ve-core` depends
 * on nothing, `ts-rs` included, so a type that crosses IPC is declared on this
 * side of the boundary and converted here.
 */
export type MeasurementKind = "dividers" | "passage" | "rings";
