// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NrtSkipped } from "./NrtSkipped";
import type { ProjectSummary } from "./ProjectSummary";

/**
 * What an import did.
 */
export type NrtOutcome = { 
/**
 * The project, with the layers that arrived.
 */
project: ProjectSummary, 
/**
 * The products that did not.
 */
skipped: Array<NrtSkipped>, };
