// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StampSpace } from "./StampSpace";

/**
 * One object's footprint under a drag, in geographic coordinates.
 */
export type ObjectOutline = { "kind": "swept", 
/**
 * Chains of `[lon, lat]` points.
 */
chains: Array<Array<[number, number]>>, 
/**
 * The stamp's radius in kilometres, as the map draws sizes.
 */
radius_km: number, 
/**
 * Whether the stamp is square.
 */
square: boolean, 
/**
 * Which space the stamp is a circle in (spec.md 3.5).
 */
space: StampSpace, } | { "kind": "ring", 
/**
 * The ring, in order; the closing edge is implied.
 */
points: Array<[number, number]>, };
