// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One object, as the layer panel sees it.
 */
export type ObjectNode = { 
/**
 * Stable identity.
 */
id: bigint, 
/**
 * User-editable name.
 */
name: string, 
/**
 * Which tool made it, e.g. `"brush"`.
 */
tool: string, 
/**
 * Display name of the tool.
 */
tool_label: string, 
/**
 * Whether it contributes at the step being viewed.
 */
active_here: boolean, 
/**
 * First step of its lifetime, inclusive.
 */
start_step: number, 
/**
 * Last step of its lifetime, inclusive.
 */
end_step: number, };
