// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which line of a measurement a drawn path is, and therefore how it is drawn.
 */
export type PathKind = "great_circle" | "rhumb" | "ring";
