// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend needs to know about the open project.
 */
export type ProjectSummary = { 
/**
 * Display name.
 */
name: string, 
/**
 * Where it lives on disk; absent until first saved.
 */
path: string | null, 
/**
 * Whether there are changes not yet written to disk.
 */
dirty: boolean, 
/**
 * `"wind"` or `"current"`.
 */
field_kind: string, 
/**
 * Grid spacing in degrees.
 */
resolution_deg: number, 
/**
 * Human-readable grid spacing, e.g. `"0.25°"`.
 */
resolution_label: string, 
/**
 * Grid columns.
 */
grid_ni: number, 
/**
 * Grid rows.
 */
grid_nj: number, 
/**
 * Hours between time steps.
 */
step_hours: number, 
/**
 * Number of time steps.
 */
step_count: number, 
/**
 * When step 0 is, as seconds since the Unix epoch, if set (spec.md 9.1).
 */
start_unix_s: bigint | null, 
/**
 * `"from"` or `"toward"`: how directions are shown (spec.md 3.3).
 */
direction_convention: string, 
/**
 * Knots at the top of the speed colour ramp (spec.md 5.3, M15).
 *
 * The project's, so two people opening one file see the same map. Tiles
 * carry speed and not colour, so changing it costs no render.
 */
colour_scale_knots: number, 
/**
 * Number of layers.
 */
layer_count: number, 
/**
 * Number of objects across all layers.
 */
object_count: number, 
/**
 * Document revision, bumped on every change.
 *
 * Tile URLs carry it, so an edit makes previously fetched tiles
 * unreachable rather than stale.
 */
revision: bigint, 
/**
 * Whether there is anything to undo.
 */
can_undo: boolean, 
/**
 * Whether there is anything to redo.
 */
can_redo: boolean, };
