// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyValue } from "./PropertyValue";

/**
 * One property, described well enough for the inspector to render it.
 */
export type PropertyView = { 
/**
 * Identifier, e.g. `"speed"`.
 */
id: string, 
/**
 * Inspector label.
 */
label: string, 
/**
 * Value at the step being viewed.
 */
value: PropertyValue, 
/**
 * Display unit: `"speed"`, `"kilometres"`, `"degrees"`, `"percent"` or `"none"`.
 *
 * A speed is stored in m/s and shown in knots; the frontend converts
 * (`ve_core::units`).
 */
unit: string, 
/**
 * Lower bound, for numeric properties.
 */
min: number | null, 
/**
 * Upper bound, for numeric properties.
 */
max: number | null, 
/**
 * Variant names, for choices.
 */
variants: Array<string>, 
/**
 * Whether the property has keyframes.
 */
animated: boolean, };
