// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The region to capture, as the map describes it.
 *
 * Degrees throughout, because a region is map space: it is drawn on the map,
 * and what is made from one is a projected stamp (D28, D55).
 */
export type RegionShape = { "kind": "rect", 
/**
 * Centre, `[lon, lat]`.
 */
centre: [number, number], 
/**
 * Half-extent east-west, in degrees.
 */
half_width_deg: number, 
/**
 * Half-extent north-south, in degrees.
 */
half_height_deg: number, } | { "kind": "disc", 
/**
 * Centre, `[lon, lat]`.
 */
centre: [number, number], 
/**
 * Radius in degrees.
 */
radius_deg: number, } | { "kind": "polygon", 
/**
 * Vertices in order, `[lon, lat]`. Closed implicitly.
 */
points: Array<[number, number]>, };
