// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectOutline } from "./ObjectOutline";

/**
 * Liquify's moved boundary and a surface-following line joining the centres.
 */
export type RelocationOutline = {
/**
 * The translated source perimeter.
 */
destination: ObjectOutline,
/**
 * Sampled in the object's own frame, then lifted onto the globe.
 */
connection: Array<[number, number]>, };
