// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress, emitted as the `render://progress` event when a tile lands.
 */
export type RenderProgress = { 
/**
 * The revision being rendered.
 */
revision: bigint, 
/**
 * The step the tile belongs to.
 */
step: number, };
