// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A small screen-aligned grid in projected degree coordinates.
 */
export type SelectionPreviewRequest = { 
/**
 * Selected object identities.
 */
objects: Array<bigint>, 
/**
 * The current frame.
 */
step: number, 
/**
 * Reject a preview from a stale document.
 */
revision: bigint, 
/**
 * First column's western edge.
 */
west: number, 
/**
 * First row's northern edge, in projected degrees.
 */
north: number, 
/**
 * Projected width and height in degrees.
 */
across: number, 
/**
 * Vertical extent in projected degrees.
 */
down: number, 
/**
 * Frozen map space: 1 equirectangular, 2 Mercator, 3 Miller.
 */
space: number, 
/**
 * Pixel columns, at most 512.
 */
width: number, 
/**
 * Pixel rows, at most 512.
 */
height: number, };
