// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Perimeter controls in geographic coordinates, only requested in edit mode.
 */
export type ShapeControls = { 
/**
 * The object being edited.
 */
object: bigint, 
/**
 * The sampled project step.
 */
step: number, 
/**
 * Revision used to reject a stale drag after undo or another edit.
 */
revision: bigint, 
/**
 * Closed contours of [longitude, latitude] controls.
 */
rings: Array<Array<[number, number]>>, 
/**
 * Whether each point has its own key at this frame.
 */
keyed: Array<Array<boolean>>, };
