// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutAction } from "./ShortcutAction";

/**
 * One binding: an action, the key that performs it, and its modifiers.
 */
export type Shortcut = { 
/**
 * What it does.
 */
action: ShortcutAction, 
/**
 * For [`ShortcutAction::Tool`], the tool's wire name; empty otherwise.
 */
tool: string, 
/**
 * The key, as the browser's `KeyboardEvent.key` lowercased: a letter, or
 * a name like `arrowleft` or `" "`.
 */
key: string, 
/**
 * Whether the binding wants shift held.
 */
shift: boolean, 
/**
 * Whether the binding wants alt (option) held.
 *
 * Added with the nudge (D67): the arrows are the timeline's bare, the
 * nudge's shifted, and the map's pan needed a third modifier that the
 * window does not own. The chord spelling grows one word and the table
 * stays one table with one collision rule.
 */
alt: boolean, };
