// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutAction } from "./ShortcutAction";

/**
 * One binding: an action, the key that performs it, and its modifiers.
 */
export type Shortcut = { 
/**
 * What it does.
 */
action: ShortcutAction, 
/**
 * For [`ShortcutAction::Tool`], the tool's wire name; empty otherwise.
 */
tool: string, 
/**
 * The key, as the browser's `KeyboardEvent.key` lowercased: a letter, or
 * a name like `arrowleft` or `" "`.
 */
key: string, 
/**
 * Whether the binding wants shift held.
 */
shift: boolean, };
