// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What reducing the timeline would delete (spec.md 4.1).
 */
export type ShrinkImpact = { 
/**
 * Keyframes past the new end.
 */
keyframes: number, 
/**
 * Objects whose lifetime will be clamped.
 */
clamped_ranges: number, 
/**
 * Every object touched, by name.
 */
objects: Array<string>, };
