// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionDependency } from "./OptionDependency";

/**
 * The km/px control a tool offers, and when it is live.
 *
 * The unit *is* the `stamp_space` control (spec.md 3.5): px asks for a shape
 * on the map and km for one on the ground, so offering the space beside the
 * unit would be two controls for one property, and the space would be the one
 * that did nothing. `stamp_space` is therefore not among a tool's options, and
 * this stands in its place — carrying the same dependency rules, so a control
 * the mode makes inert is still hidden.
 */
export type Sizing = { 
/**
 * What makes the unit inert, if anything.
 *
 * The shape fill's freehand polygon is the case: its vertices are placed
 * geographically one by one, so it has no size and no space to size it in.
 */
depends_on: Array<OptionDependency>, };
