// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A centred slider's labelling (M29), as the schema declares it.
 */
export type SliderView = { 
/**
 * The label at the left end.
 */
low_label: string, 
/**
 * And at the right end.
 */
high_label: string, 
/**
 * Whether the stored value's positive end is the left one.
 */
reversed: boolean, };
