// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend needs to draw one SST layer.
 */
export type SstLayerView = { 
/**
 * The product, as `ve_zarr::Product::id` spells it.
 */
product: string, 
/**
 * Which day each step shows, as that day's tile token; `None` where the
 * layer shows nothing.
 */
tokens: Array<bigint | null>, };
