// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tool made the gesture (spec.md 6.2).
 *
 * A wire mirror of [`ToolKind`], which cannot derive `TS` from another crate.
 */
export type Tool = "brush" | "circle" | "shape_fill" | "eraser" | "clone_stamp" | "curve";
