// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterpolationView } from "./InterpolationView";
import type { KeyframeView } from "./KeyframeView";
import type { PropertyValue } from "./PropertyValue";

/**
 * One property's track: its base, its keys, and what the timeline may do to it.
 */
export type TrackView = { 
/**
 * The property id, as the inspector spells it.
 */
property: string, 
/**
 * Its label.
 */
label: string, 
/**
 * The value used when there are no keys.
 */
base: PropertyValue, 
/**
 * Every key, in step order.
 */
keys: Array<KeyframeView>, 
/**
 * The interpolations this property's kind allows (spec.md 4.5).
 */
interpolations: Array<InterpolationView>, 
/**
 * Whether a key sits on the step being viewed.
 */
keyed_here: boolean, 
/**
 * Whether the value at the step being viewed comes from interpolation
 * between keys rather than from a key or the base (spec.md 9.3).
 */
interpolated_here: boolean, };
