// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One numeric component of a property, sampled at every step.
 *
 * A scalar or an angle has one; a position has two, longitude and latitude,
 * which share an axis because they share a unit.
 */
export type TrackSeries = { 
/**
 * Empty for a property with a single component; otherwise which one.
 */
label: string, 
/**
 * Display unit, in [`crate::document::PropertyView`]'s vocabulary. The
 * frontend converts — a speed is sampled in m/s and graphed in the preferred speed unit.
 */
unit: string, 
/**
 * The value at every step of the project, in step order.
 */
values: Array<number>, };
