// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the map should look.
 */
export type ViewFocus = { lon: number, lat: number, 
/**
 * Screen pixels per degree; null keeps the current zoom.
 */
px_per_deg: number | null, };
