export type Parameter = readonly [name: string, description: string];
export interface HelpImage { path: string; caption: string }
export interface HelpSection {
  heading: string; paragraphs?: string[]; parameters?: readonly Parameter[];
  steps?: string[]; images?: HelpImage[];
}
export interface HelpTopic {
  id: string; group: string; title: string; paragraphs: string[];
  steps?: string[]; parameters?: readonly Parameter[]; images?: HelpImage[];
  sections?: HelpSection[]; related?: string[];
}
const shot = (path: string, caption: string): HelpImage => ({ path: `reference/${path}.png`, caption });
const feather: Parameter = ["Feather", "Softens the boundary. 0 gives a hard edge and is the default for new tools; 1 uses the full available feather region. A modifier fades its effect toward the unchanged field; a painting tool fades its contribution. Existing objects retain their saved value."];
const edge: Parameter = ["Edge: Blend / Replace", "Blend mixes the new vector with the existing vector through a soft edge. Replace fades the new vector toward calm instead. The hard interior uses the new vector in either mode. Undefined source cells stay transparent in both modes."];
const size: Parameter = ["Size and units", "Brush diameter or square width. px gives consistent screen proportions at creation; km / nm gives a ground distance. Later zooming does not resize existing objects. The chosen unit also applies to the tool's other size controls."];
const brushShape: Parameter = ["Brush shape: Circle / Square", "Chooses the stamp swept along the gesture. Circle makes round ends; Square sweeps square stamps. This geometry choice is fixed after drawing; shape animation can reshape an existing object."];
const speed: Parameter = ["Speed", "Vector magnitude in the global speed unit. Zero paints defined calm data, which is different from an empty area."];
const direction: Parameter[] = [
  ["Direction mode", "Constant uses one compass direction. Toward point aims at a target separately at every location; Away from point reverses that direction. Only relevant options are shown."],
  ["Direction", "Degrees in the project's from / toward convention. North is 0°, east 90°, south 180°, west 270°. With wind 'from', 270° paints wind moving east."],
  ["Target / Pick on map", "Enter longitude then latitude, or press Pick on map and click the target. Positive longitude is east; positive latitude is north. That picking click places the target instead of painting."],
  ["Direction to target: Great circle / Rhumb line", "Great circle uses the local bearing of the shortest spherical route. Rhumb line uses a constant compass bearing to the target. The two can differ substantially on long routes and at high latitudes."],
  ["Angle relative to target", "Offsets the resulting direction from −180° to +180°. Zero aims directly toward or away from the target. Positive angles turn clockwise; negative angles turn counterclockwise."],
];
const eyedropper: Parameter = ["Eyedropper", "Click it, then a defined map location, to copy speed and direction into the tool. It samples visible data of the active field kind. It is available for single-vector modes, rather than two-ended gradients."];
const modifier = "An edit object changes data below it in its own layer. It cannot create flow over undefined data. Place it above the objects it should affect. Its transform, amount, lifetime, and supported properties can be animated.";

/** Bundled offline reference. Screenshot values are examples, not defaults. */
export const TOPICS: HelpTopic[] = [
  { id: "workspace", group: "Workspace", title: "Get started", paragraphs: [
    "VectorEffects creates animated wind and surface-current fields from painted objects, GRIB files, historical archives, and captured macros. The canvas owns the base map. Empty layers are transparent; only defined data and image overlays cover what is below.",
    "This searchable reference works offline. Choose a page on the left and click screenshots to inspect them at full size. Screenshots show example projects from an earlier beta: nonzero feather values are examples, Circle's angle now uses a slider, and Path's former Absolute option is now Constant.",
  ], steps: ["Choose New and set a grid resolution, hours per frame, and frame count.", "Select an unlocked layer, choose Brush, set speed and direction, and drag on the map.", "Select the new object to inspect or animate it.", "Save as .veproj to preserve editable objects. Use Export GRIB for vector data to use in another program."],
    images: [shot("overview/overview", "The map, tool options, layers, inspector, history, and timeline.")], related: ["projects", "tools", "layers", "animation", "export"] },
  { id: "projects", group: "Workspace", title: "Projects, saving, and recovery", paragraphs: ["A project stores its grid, timeline, layers, geometry, and animation. Keep imported source files at their referenced paths when reopening or moving a project. Keep the .veproj file as your editable original after exporting."],
    parameters: [["New: Name", "Names the project. Set each painted layer’s field kind in the layer panel."], ["Resolution", "Geographic grid spacing. A finer grid resolves smaller details but increases evaluation time and export size."], ["Step hours / Steps", "Simulated hours between frames and total frame count. These are distinct from playback frames per second."], ["Open / Recent projects", "Open a .veproj file. Recent projects lists existing files; use Open to locate a moved project."], ["Save / Save As", "Save updates the current file. Save As chooses a new path. An unsaved project needs a path first."], ["Close", "Closes the project. Unsaved work offers Save, Discard, or Cancel."], ["Autosave", "Settings can keep recovery snapshots, save directly into the project file, or leave saving manual. The trigger is every minute or fifty edits, whichever comes first. Recovery is offered after a crash."], ["Undo / Redo / History", "Reverse or reapply document edits; History describes them. A completed gesture is one edit, so one Undo removes a stroke or restores an erased region."]],
    images: [shot("overview/project_management", "Project controls and the Settings gear.")], related: ["settings", "export", "troubleshooting"] },
  { id: "view", group: "Workspace", title: "Map view and direction conventions", paragraphs: ["Pan with the hand tool and zoom with the wheel or trackpad. View settings affect presentation, not exported vectors."],
    parameters: [["Capture", "Enters macro capture mode to record a region across frames."], ["Measure", "Opens range rings, dividers, and route comparisons. Measurements do not paint vector data."], ["Glyphs", "Shows or hides directions: meteorological barbs for wind and arrows for currents."], ["Projection", "Changes how longitude and latitude are drawn, including Mercator and Miller. Ground-sized circles can look stretched; pixel-sized geometry preserves the screen shape in its creation projection."], ["Graticule", "Shows longitude and latitude reference lines."], ["Auto scale", "Fits colour scale maxima to visible data. Turn off for comparisons using fixed project scales."], ["Legend", "Shows the gradient, field kind, speed units, and scale limits."], ["Readout", "Shows pointer coordinates, sampled speed and direction, and zoom. 'No field' means undefined data."], ["Arrows versus wind barbs", "An arrow points where current goes. A wind barb points toward where wind comes from, with feathers at that end. A northerly wind's barb points north, but its flow travels south. Numeric direction convention does not reverse meteorological barbs."]],
    images: [shot("overview/view_and_global_settings", "Capture, measurement, undo/redo, and map display controls.")], related: ["targets", "settings", "measure", "divergence"] },
  { id: "layers", group: "Workspace", title: "Layers, stacking, and speed filters", paragraphs: ["The list shows the top of the stack first. Painted layers contain objects and are completely transparent where those objects define no data. The base map is beneath the stack and has no layer row. You can delete every layer; add a new layer to resume painting or use Undo to restore one."],
    parameters: [["+ / Import GRIB / Import image / Calendar", "Add a painted layer, import vectors, add a reference image, or download historical data."], ["Name / disclosure triangle", "Select the layer or expand its object list."], ["Drag handle / up and down arrows", "Reorder layers by dragging their headers or using arrows. Drag object rows to reorder them, or onto another layer to move them. Edit and clone objects read what is below them in that layer."], ["Eye / lock", "Hide a layer or prevent editing its objects. Unlock before drawing or transforming."], ["Field", "Selects the kind for painted layers. Imported layers report their source kind. Wind and currents remain separate fields."], ["Speed filter: minimum / maximum", "Enable an inclusive speed range in the display units. Values outside it become transparent. Filtering is applied after the layer's objects and edits; all layer types support it. Image thresholds use vector speed at image positions."], ["Duplicate / ×", "Duplicate an object, delete an object, or delete a layer and its objects. Undo restores document deletions."]],
    images: [shot("overview/layer_panel", "Layer controls and the optional speed filter.")], related: ["selection", "imports", "history", "clone"] },
  { id: "selection", group: "Workspace", title: "Selection, properties, and transforms", paragraphs: ["Select from the layer panel or with the selection tool; Shift-click extends selection. Only selected objects appear in the moving preview, even if other objects overlap their bounds. Choosing a layer or drawing a region can change selection scope."],
    parameters: [["Position / Pick", "Anchor longitude and latitude. Pick assigns it from a map click. Dragging moves the anchor; keying Position makes it travel."], ["Scale", "Resizes around the anchor. 100% is the original size. It changes geometry, not vector speed."], ["Rotation", "Rotates the object and its field about the anchor. The Rotation edit tool instead turns vectors without moving the field's footprint."], ["Visible", "Enables the object; key it to switch it on and off over time."], ["Transform handles", "Move, rotate, or scale the selection at the current frame, following the keyframe rules."], ["Property diamonds", "Add a key at the selected frame. The timeline shows the same properties and their keys."], ["Layer facts", "With no object selected, Properties describes the active layer: source, file or archive, field kind, and frame coverage."], feather, edge],
    images: [shot("overview/properties_history", "Object properties, animation diamonds, and edit history.")], related: ["animation", "shape", "tools"] },
  { id: "tools", group: "Create tools", title: "Tool basics: size, feather, and edges", paragraphs: ["Tool options set new gestures; the inspector edits existing objects. After changing an option, the next map click uses the tool. Pick on map and the eyedropper deliberately reserve a click for picking or sampling.", "A completed gesture becomes an object; compatible strokes may merge according to the active tool and settings. Create tools paint vectors, while edit tools modify data below them. Only options meaningful in the current mode are shown."],
    parameters: [size, brushShape, feather, edge, eyedropper, ["Pixel geometry", "px means pixels at creation, including at high latitudes. Saved geography stays anchored when you pan, zoom, or change projection."], ["Fixed geometry choices", "Choices such as the original stamp shape are fixed after creation. Use shape animation to reshape the object rather than changing its construction mode."]],
    images: [shot("overview/tool_bar", "Hand, select, eraser, insert macro, brush, circle, shape, clone, path, mask, intensity, divergence/convergence, rotation, warp, and liquify.")], related: ["brush", "circle", "path", "eraser"] },
  { id: "brush", group: "Create tools", title: "Brush", paragraphs: ["Drag to paint a swept circle or square; click for a single stamp. Use a constant flow or aim each vector toward or away from a target. The edge follows Feather and Edge mode."],
    parameters: [brushShape, size, speed, ...direction, feather, edge, eyedropper],
    images: [shot("create_tools/brush_tool_constant", "A brush with constant wind direction. Feather is an example value.")], related: ["targets", "tools", "animation"] },
  { id: "targets", group: "Create tools", title: "Target bearings and angle offsets", paragraphs: ["Target modes vary direction across an object. They appear on Brush and the constant-vector Shape mode. Moving or animating the target changes the aiming point without redrawing the shape."],
    parameters: direction,
    steps: ["Choose Toward point or Away from point.", "Enter coordinates or use Pick on map.", "Choose Great circle or Rhumb line.", "Leave Angle relative to target at 0 for direct aiming, or enter an offset.", "Paint and inspect several locations with the readout; wind barbs show the from direction."],
    images: [shot("create_tools/brush_tool_point", "Target coordinates, route choice, and angular offset.")], related: ["view", "brush", "fill", "measure"] },
  { id: "circle", group: "Create tools", title: "Circle stamp", paragraphs: ["Click to place circular flow around the pointer. Choose a disc, ring, or disc with radial speed gradient. The angle tilts the flow inward or outward while preserving its chosen speed."],
    parameters: [["Fill: Filled / Perimeter / Filled gradient", "Filled paints the disc at Speed. Perimeter leaves its centre undefined. Filled gradient varies speed from centre to edge."], ["Diameter / Ring width", "Outer diameter and perimeter-band thickness. Both use the selected px or ground unit."], speed, ["Speed (centre) / Speed (edge)", "Endpoint speeds for Filled gradient. A zero centre is defined calm, rather than an empty hole."], ["Rotation: CW / CCW", "Clockwise or counterclockwise circulation at zero tangent angle."], ["Angle from tangent", "Slider from −90° to +90°. −90° points directly inward; 0° follows the tangent; +90° points outward. Intermediate values make spiralling flow. The readout is degrees."], feather, edge],
    images: [shot("create_tools/circle_tool", "Circle parameters. Angle from tangent now uses a −90° to +90° slider.")], related: ["tools", "divergence", "shape"] },
  { id: "fill", group: "Create tools", title: "Shape fill and vector gradients", paragraphs: ["Paint a dragged preset or a polygon. The outline determines where data exists; Vector mode determines the vectors inside. A gradient blends endpoint vectors, so different endpoint directions can also change the speed between them."],
    parameters: [["Shape: Polygon / Square / Rectangle / Circle", "Click polygon vertices and finish with Enter or double-click. Drag out a preset. Escape cancels an unfinished construction."], ["Shape in", "Ground units define geographic geometry; px defines the shape in the current projection's screen plane."], ["Vector mode: Constant / Gradient", "Constant uses one speed and the direction mode. Gradient uses start and end vectors distributed across the shape."], speed, ...direction, ["Speed (start) / Speed (end)", "Magnitudes at opposite ends of the gradient."], ["Direction (start) / Direction (end)", "Endpoint directions in the project's from / toward convention."], ["Gradient axis", "Geometric bearing from the gradient's start toward its end. It is an axis, not a wind-from direction."], feather, edge],
    images: [shot("create_tools/shape_fill", "A polygon with a vector gradient.")], related: ["targets", "shape", "selection"] },
  { id: "clone", group: "Create tools", title: "Clone stamp and transparency", paragraphs: ["Clone copies vectors below itself in the same layer, not the basemap or background colours. Source holes remain transparent during preview and after release. A genuinely defined zero-speed source still copies as calm.", "Source objects are evaluated at the current frame, so their changes and animation can change the clone. Objects above the clone do not become its source."],
    parameters: [brushShape, size, ["Source / Pick on map", "Source anchor coordinates. Choose them before painting the destination."], ["Offset: Aligned", "Maintains the offset from destination anchor to source. As the sampling location moves, its source moves by the corresponding amount."], ["Offset: Fixed", "Restarts sampling around the chosen source for each stamp along the stroke, repeatedly applying that source area."], feather, edge],
    steps: ["Activate the layer containing the source objects.", "Choose Clone stamp and pick a source with defined data.", "Set size, offset mode, and feather.", "Paint the destination. Undefined source cells leave it unchanged."],
    images: [shot("create_tools/clone_stamp", "Source and Offset controls on a cloned field.")], related: ["layers", "tools", "troubleshooting"] },
  { id: "path", group: "Create tools", title: "Path / curve tool", paragraphs: ["Paint a corridor for a jet, front, or channel. Place route points and finish with Enter or double-click. Escape abandons an unfinished path. Flow can follow the route or stay constant."],
    parameters: [["Curve: Polyline / Bézier", "Polyline joins vertices with straight segments. Bézier provides curved segments and control handles."], ["Width", "Full corridor width in px or ground units."], speed, ["Direction mode: Constant", "One compass direction across the corridor. Earlier versions called this Absolute; behavior is unchanged."], ["Direction mode: Relative to path", "Uses the local tangent. Direction 0° follows point order, 180° flows back along it, and 90° turns across it."], ["Direction", "A compass bearing in Constant mode, using the project convention; a geometric tangent offset in Relative to path mode. Offsets are not converted into wind-from bearings."], feather, edge, eyedropper],
    images: [shot("create_tools/path_tool", "A corridor whose vectors follow its route.")], related: ["tools", "shape", "animation"] },
  { id: "mask", group: "Edit tools", title: "Mask", paragraphs: ["A mask removes coverage from earlier data in its layer, revealing lower layers. It remains an editable, animatable object. Erasing instead removes geometry destructively."],
    parameters: [brushShape, size, feather, ["Invert", "Off masks inside the footprint. On masks outside it, confining the layer's earlier data to that region."], edge],
    images: [shot("edit_tools/mask_tool", "A mask crossing painted shapes.")], related: ["eraser", "layers", "shape"] },
  { id: "intensity", group: "Edit tools", title: "Intensify / reduce", paragraphs: [modifier, "Changes speed while preserving direction. A zero vector stays calm."],
    parameters: [size, ["Amount", "Slider −100% to +200%. Zero does nothing; +100% doubles speed; +200% triples it; −50% halves it; −100% makes defined calm. Feather blends toward the original speed at the edge."], feather],
    images: [shot("edit_tools/intensify_tool", "Increasing speed under a modifier footprint.")], related: ["divergence", "rotation", "layers"] },
  { id: "divergence", group: "Edit tools", title: "Divergence / convergence", paragraphs: [modifier, "Divergence bends flow away from the footprint centre or stroke centreline; convergence bends toward it. Speed is preserved. Wind barbs point into the incoming wind: their shafts may point inward when the actual flow diverges.", "For northward flow east of a stamp centre, Divergence adds an eastward component; Convergence adds a westward component."],
    parameters: [size, ["Amount: Divergence (outward)", "Left side bends flow outward. A larger amount adds a stronger radial component before restoring the original speed."], ["Amount: Convergence (inward)", "Right side bends flow inward. The centre is neutral. Percentage is effect strength, not a speed change."], feather],
    images: [shot("edit_tools/convergence_divergence_tool", "Divergence over wind data; barbs indicate the from direction.")], related: ["view", "circle", "rotation"] },
  { id: "rotation", group: "Edit tools", title: "Rotation edit tool", paragraphs: [modifier, "Turns vectors in place while keeping their footprint and spatial features where they were."],
    parameters: [size, ["Turn: Clockwise / Counterclockwise", "Which way to rotate the underlying flow."], ["Amount", "0° to 180°. Zero is neutral, 90° turns sideways, and 180° reverses direction. Speed is preserved."], feather],
    images: [shot("edit_tools/rotation_tool", "Turning underlying vectors by 30°.")], related: ["selection", "warp", "intensity"] },
  { id: "warp", group: "Edit tools", title: "Warp and liquify", paragraphs: [modifier, "Warp moves sampling positions so field features can be pushed or twisted. Liquify applies a local drag deformation. Use an object transform to move a whole object as a unit."],
    parameters: [size, ["Warp: Push", "Displaces the field toward Push to. Shift-drag sets the pull from the anchor to its destination."], ["Push to", "Destination coordinates shared by every frame. Push to cannot be keyed; Position can still animate the object’s placement."], ["Warp: Twist", "Twists sampling about the anchor."], ["Twist", "Signed angle −360° to +360°. Zero is neutral; the sign changes the sense of rotation."], ["Liquify: Strength", "0% applies no displacement; 100% applies the full drag."], feather],
    images: [shot("edit_tools/warp_tool", "Twist mode with size, angle, and feather.")], related: ["rotation", "selection", "shape"] },
  { id: "eraser", group: "Edit tools", title: "Eraser and destructive cuts", paragraphs: ["Erasing removes geometry from objects or data in the active layer. It does not paint background or zero-speed values. Undo restores the cut; use a mask for a separate, removable cutout object.", "Cuts remain removed as animated perimeters change. Selecting Eraser leaves shape editing and hides the perimeter dots."],
    parameters: [brushShape, size, feather], steps: ["Activate and unlock the intended layer.", "Choose Circle or Square and a px or ground size.", "Use Feather 0 for a clean cut or increase it for softness.", "Drag across the unwanted region. Undo restores it."],
    images: [shot("utility_tools/eraser", "A 400-pixel eraser in Mercator.")], related: ["mask", "shape", "layers"] },
  { id: "animation", group: "Animation", title: "Keyframes and motion", paragraphs: ["The playhead chooses the frame being edited. Expand an object to see its animatable properties. Diamonds are keys; between them values follow their interpolation. Move to a frame, add a diamond, and edit the inspector or map handles.", "Auto-key can create keys while editing. Direction modes, Circle Fill, Clone Offset, Mask Invert, and Warp mode/Push to apply to the whole object and cannot be keyed. Once a property has keys, editing at another frame adds a key rather than changing the whole animation."],
    parameters: [["Play / Pause / Stop", "Play advances from the current frame; Pause holds it; Stop returns to the start."], ["Loop", "Repeats playback after the last frame."], ["steps/s", "Requested display frames per second, separate from simulated hours per frame. Unprepared imported data may need time to load."], ["Auto-key", "Controls automatic key creation when editing animatable properties."], ["Steps", "Total frame count. Shortening the timeline can remove later keys and requires confirmation."], ["Time / Add start time / ×", "Sets or removes the UTC start time. Without it the ruler shows relative hours; with it, absolute UTC dates are available."], ["Readiness strip", "Shows prepared frames. Large imported datasets need time for initial preparation."], ["Property graph / easing", "Expand a property to inspect its values over time. Right-click a key to select available easing for the segment leaving it."], ["Key selection", "Click keys to select them, drag to move them, and Delete to remove them. Selected keys take precedence over object deletion."]],
    images: [shot("overview/timeline", "Transport, rate, auto-key, time, and lifetime bars."), shot("timeline/keyframes", "Property keys and intermediate-frame dots.")],
    sections: [{ heading: "Move at a constant speed", paragraphs: ["Click →+ on Position. Motion begins at the selected frame and ends at the next position key, or the object's last frame if no later key exists."], parameters: [["Direction toward (° true)", "Travel direction: 0° north, 90° east, 180° south, 270° west. Always toward, independently of wind-from display."], ["Speed", "Travel speed in the global speed unit."], ["Add motion / Cancel", "Creates the stated interval's path or cancels. Existing keys in the interval require confirmation before replacement. One Undo restores the previous track."]], images: [shot("timeline/position_constant_motion", "The →+ control on Position."), shot("timeline/position_constant_motion_dialog", "Travel direction and speed for the stated interval.")] }],
    related: ["spans", "shape", "links", "motion-vectors"] },
  { id: "spans", group: "Animation", title: "Object lifetime: start and end frames", paragraphs: ["The lifetime bar sets inclusive frames in which an object contributes. It is separate from animation keys: an object can have a long motion track but be active for only part of it."],
    parameters: [["Start handle", "Drag the left grip to set the first active frame. Its clickable area extends beyond the thin painted bar."], ["End handle", "Drag the right grip to set the last active frame."], ["Bar body", "Drag to move the entire interval while preserving its length. Clicking without movement selects the object."], ["Released preview", "The bar holds its released position while document rows refresh, avoiding a snap back to the old range."]],
    images: [shot("timeline/keyframes", "The lifetime bar is above the individual property tracks.")], related: ["animation", "macros", "shape"] },
  { id: "shape", group: "Animation", title: "Animate an object's shape", paragraphs: ["Shape animation is an editing mode for create and edit objects, excluding captured macros and patches. Perimeter points retain their identity between keys and appear only while the object's shape button is enabled."],
    steps: ["Select the object and click the perimeter icon beside its timeline name.", "At the desired frame, drag dots and add a Shape key with its diamond when needed.", "Visit another frame and move the dots again.", "Scrub to inspect the changing outline.", "Click the perimeter icon again or choose another tool to leave the mode and hide the dots."],
    parameters: [["Perimeter dots", "Positions along the outline at the current frame. They belong to the object's animation, not separate objects."], ["Shape track / diamond", "Stores an outline at a frame. Further keys define outlines to interpolate between."], ["Eraser interaction", "Cuts remain destructive and are not restored just because the outline later changes."]],
    images: [shot("timeline/shape_keyframes", "Perimeter dots and a keyed Shape track.")], related: ["animation", "eraser", "selection"] },
  { id: "links", group: "Animation", title: "Link position or rotation", paragraphs: ["A follow link makes a property follow the corresponding property of a primary object, keeping features moving or turning together."],
    steps: ["Expand both objects.", "Click the follower's Position or Rotation link control.", "Click the primary's row for that property. Clicking the armed control again cancels.", "Edit the primary's track. Click the active link to unlink before making an independent track."],
    parameters: [["Link control", "Arms, reports, or removes a follow link. Dragging between corresponding rows is also supported."], ["Followed diamonds", "Represent the primary's animation. Edit them on the primary's row rather than treating them as independent follower keys."]],
    images: [shot("timeline/link_motion_to_object", "A followed Position row with the unlink tooltip.")], related: ["animation", "motion-vectors"] },
  { id: "motion-vectors", group: "Animation", title: "Add object motion to its vectors", paragraphs: ["Moving a shape and changing its painted vectors are separate choices. Motion contribution adds the object's movement to the field. It does not create a path: first animate transforms, then enable their contributions.", "Motion vectors combine with the original vectors, so both speed and direction can change."],
    parameters: [["Motion contribution (⇢)", "Adds motion associated with that transform. Position contributes travel velocity; available Scale and Rotation contributions account for their changing transforms."], ["Constant motion (→+)", "Creates a Position path. This differs from adding motion to painted vectors."], ["Static transform", "A transform that does not change contributes no movement, even with the control on."]],
    images: [shot("timeline/add_motion_vectors", "Enabled motion contribution on a keyed Position track.")], related: ["animation", "links", "macros"] },
  { id: "imports", group: "Data and macros", title: "GRIB files and reference images", paragraphs: ["GRIB import adds supported wind and current fields as separate layers. Each frame uses the source time assigned to that project step. Images are visual references and contain no exportable vector data."],
    parameters: [["Import GRIB", "Choose the file; inspect its field, frames, path, and coverage in layer facts. Keep it available when reopening."], ["Imported frame cells", "Select frames in the source layer's timeline row. Copy, paste, and delete act on those frames instead of object keys. Shift extends a run."], ["Import image", "Choose a reference image and its geographic placement."], ["Image opacity", "Controls how strongly the image covers the canvas."], ["Speed filter", "Restricts field coverage to an accepted range; image filters use speed at image locations."], ["Missing file", "Restore its referenced path or import it again. Missing data is not treated as real calm."]], related: ["history", "layers", "export"] },
  { id: "history", group: "Data and macros", title: "Download historical wind and currents", paragraphs: ["The layer panel's calendar opens historical import. Choose UTC dates and archives; each becomes a layer. Cached downloads can be reused when revisiting or retrying a request."],
    parameters: [["Start (UTC) / End (UTC)", "Inclusive whole-hour endpoints. Longer intervals mean more frames and downloads; review the workload summary."], ["Set the timeline's start", "Aligns project start to the first requested UTC time."], ["ERA5 wind", "Selects the offered 10 m wind archive."], ["GlobCurrent", "Selects the offered total surface-current archive."], ["Import / Cancel", "Starts the selected request or leaves the project unchanged before starting."], ["Progress", "The bottom panel reports downloading and preparation. Both archives or longer ranges increase work."], ["Retry download", "Appears beside a failure in the bottom panel and repeats the saved request, reusing cached data. Browsing the map does not dismiss it."]],
    images: [shot("layers/import_history", "UTC dates, archive choices, alignment, and workload summary.")], related: ["imports", "animation", "capture", "troubleshooting"] },
  { id: "capture", group: "Data and macros", title: "Record and preview a macro", paragraphs: ["Capture records a region's vector data over frames, optionally including its movement. It uses the active field kind; basemap colours and images are not vector data."],
    steps: ["Choose the source field and first frame.", "Enter capture mode, choose a shape, and draw the region.", "Enable Record movement if needed, then Start capture.", "Visit later frames and move the region to follow the feature.", "Finish recording to preview the frame range.", "Use Edit macro to revise it, Save macro to name and store it, or Cancel to abandon it."],
    parameters: [["Shape", "Region outline delimiting the captured data."], ["Record movement", "Keeps the capture region's movement across visited frames."], ["Recording keys", "Region positions at visited steps. Scrub to inspect the path between them."], ["Preview", "Plays the captured data in isolation. Click the map to preview placement elsewhere."], ["Edit macro / Save macro / Cancel", "Revise, save to the library, or abandon capture. Other document edits are disabled while recording or previewing."]],
    images: [shot("creating_macros/create_macro_select_frame_and_area", "Choose the first frame and region."), shot("creating_macros/record_macro_end", "Move the region at a later frame."), shot("creating_macros/record_macro_preview", "Preview before saving.")], related: ["macros", "animation", "history"] },
  { id: "macros", group: "Data and macros", title: "Insert macros and interpolate missing frames", paragraphs: ["Choose Insert macro, select a library entry, and click to place it at the current frame. The hover outline previews placement in the selected painted layer only. A crossed cursor means the macro has no data matching that layer’s wind/current type, or the layer cannot accept it; no object is placed in another layer. A macro with both fields uses the selected layer’s matching field. It becomes an object with editable transforms and lifetime.", "Interpolation strategy appears when recorded frames are farther apart than project frames, such as a three-hourly macro in an hourly project. This strategy applies to the whole macro and cannot be animated."],
    parameters: [["Macro selector / Refresh", "Select a library entry by name, duration, frame count, and movement indicator. Refresh reloads library contents."], ["Repeat Frames", "Default: holds the latest recorded frame until the next one."], ["Empty Frames", "Shows no macro data on intermediate frames, revealing what is beneath."], ["Interpolate", "Blends u and v separately and interpolates recorded movement. Component interpolation avoids spinning a direction through a full turn at a bearing wrap."], ["Loop", "Repeats the recorded sequence within the object's active lifetime."], feather, edge, ["Library directory", "Configured in Settings. Inserted projects keep their own macro frames, so deleting the library does not remove macros already in a project."]],
    images: [shot("creating_macros/insert_macro_hover", "The insertion outline follows the pointer."), shot("creating_macros/insert_macro_clicked", "An inserted macro and its lifetime bar.")], related: ["capture", "spans", "motion-vectors", "settings"] },
  { id: "measure", group: "Measurements", title: "Great-circle and rhumb-line comparison", paragraphs: ["Choose Great circle / rhumb under Measure and click two endpoints. Great circle is the shortest spherical route with changing local bearing. A rhumb line holds a constant bearing and is generally longer."],
    parameters: [["GC label", "Distance and initial bearing of the great-circle route."], ["RL label", "Distance and constant bearing of the rhumb line."], ["Endpoints", "Drag to revise the comparison."], ["Alt-click a point", "Removes that measurement."], ["Clear great circle / rhumb", "Removes all route comparisons, retaining other measurements."], ["Clear all", "Removes all measurement annotations, not vector objects."]],
    images: [shot("global_utility_tools/great_circle_rhumb_line", "Great-circle curve and dashed rhumb line between the same endpoints.")], related: ["targets", "rings", "dividers"] },
  { id: "rings", group: "Measurements", title: "Range rings", paragraphs: ["Choose Range rings and click a centre. The rings represent ground distances, so a projection may stretch their appearance."],
    parameters: [["Interval", "Ground distance between rings in the global distance unit."], ["Rings", "Number of rings. Outer radius equals Interval × Rings."], ["Editing the last set", "Changes update the active set. Click elsewhere to add a set; drag a centre handle to move it."], ["Alt-click a point", "Removes that ring set."], ["Clear range rings / Clear all", "Clears ring sets or every measurement type."]],
    images: [shot("global_utility_tools/range_rings", "Twenty rings at 50 nm intervals, with a 1000 nm outer radius.")], related: ["measure", "dividers", "settings"] },
  { id: "dividers", group: "Measurements", title: "Dividers and multi-leg distances", paragraphs: ["Choose Dividers and click successive waypoints. Each leg shows distance and bearing; the chain reports cumulative distance. Measurements do not alter exported vectors."],
    parameters: [["Click", "Adds a leg from the last waypoint."], ["Enter / Escape", "Finishes the current chain."], ["Waypoint handles", "Drag to revise the route and recalculate distances."], ["Alt-click a point", "Removes that measurement."], ["Clear dividers / Clear all", "Clears chains or all measurement annotations."]],
    images: [shot("global_utility_tools/dividers", "A multi-leg chain with bearings and total distances.")], related: ["measure", "rings"] },
  { id: "settings", group: "Settings and export", title: "Units, arrows, and wind barbs", paragraphs: ["Open Settings with the gear. Units and glyph styles are app preferences; project colour scales and gradients are saved in the project. Presentation choices do not change exported magnitudes or directions."],
    parameters: [["Distance: km / nm", "Converts entry and readouts between kilometres and nautical miles."], ["Speed: kt / mph / km/h", "Converts tool values, readouts, legends, and motion dialogs. Values are converted, not reinterpreted."], ["Arrows / Wind barbs", "Separate style controls and previews for each glyph type."], ["Size (%)", "Glyph length as a percentage of its normal screen size, from 25% to 300%."], ["Density", "Number and spacing of glyphs. Higher density shows more local directions but can crowd the map."], ["Line width", "Shaft and feather thickness."], ["Color / Opacity", "Glyph colour and overall transparency."], ["Fade with speed", "Lowers opacity in slower flow while keeping defined calm wind visible."], ["Drop shadow", "Adds contrast behind glyphs."], ["Shadow color / opacity", "Independent colour and transparency for the shadow."], ["Shadow X / Y (px)", "Horizontal and vertical shadow displacement in pixels."], ["Reset arrows / Reset wind barbs", "Restores the default appearance for that style."], ["Project colour scales", "Fixed wind/current maximum speeds when Auto scale is off."], ["Project gradients", "Separate wind/current colour maps selected from swatches."], ["Defaults for new projects", "Initial wind/current scale limits for projects created later."], ["Keyboard shortcuts", "Click a binding, then press its replacement combination. The displayed bindings describe your current setup."], ["Autosave / macro library", "Choose recovery, direct saving, or manual saving. Set the macro directory or delete library entries. Library deletion asks for confirmation and keeps already-inserted project macros."], ["MCP service", "Lets an AI client on this computer drive the application over the Model Context Protocol. Off by default; on, the section shows the local address, the token and a ready client configuration. Rotate token revokes the old one. The status bar shows MCP and the last tool while a client is connected."]],
    images: [{ path: "settings.png", caption: "Separate arrow and wind-barb appearance controls." }], related: ["view", "projects", "macros"] },
  { id: "export", group: "Settings and export", title: "Export GRIB2", paragraphs: ["Export GRIB writes evaluated vectors for other applications. The dialog asks for destination and forecast reference time. Originating centre and precision selectors have been removed. Every message carries 'Created with VectorEffects'.", "Export uses the project grid independently of zoom, screen size, and glyph density. Keep the .veproj file to continue editing."],
    parameters: [["Destination", "Output .grib2 path."], ["Reference date / hour (UTC)", "Forecast reference time. Frame offsets are added to get message validity times; check against the intended historical or forecast period."], ["Estimated size", "An upper bound. Sparse and constant fields can be much smaller."], ["Export / progress / cancel", "Starts and reports export, or stops it without changing the project."], ["Undefined data", "Uncovered cells use GRIB bitmaps. They are not written as zero. Deliberately painted calm remains a defined zero."], ["Wind and current", "u and v are written separately for each frame and visible field kind. Hidden layers do not contribute."], ["Memo", "Each message contains 'Created with VectorEffects' in its local-use section. A reader may not display it in ordinary forecast controls."], ["Automatic packing", "Standard 16-bit simple packing, with compact constant fields. No precision choice is required."], ["Excluded view content", "Basemap, images, glyphs, selection handles, and measurements do not become vectors."], ["Export Zarr", "Writes the same evaluated vectors as a Zarr V3 directory instead: one Float16 array of u/v wind and u/v current, chunked 72 hours by 10 degrees, Zstd compressed, with uncovered cells NaN. The array's attributes record the reference time, the step and the grid origin."]],
    images: [{ path: "export.png", caption: "The simplified export dialog with UTC reference time and destination selection." }],
    related: ["projects", "layers", "imports", "troubleshooting"] },
  { id: "troubleshooting", group: "Settings and export", title: "Troubleshooting", paragraphs: ["Check the active layer, selected frame, and field kind first. Undo helps isolate a recent edit. Save a copy before investigating a complex project."],
    parameters: [["Nothing appears", "Check visibility, lock, object lifetime, and speed filters. Edit tools need defined data below. Neutral Amount or zero Strength does nothing."], ["First click after a setting", "The next ordinary press commits numeric entry and uses the tool. Pick on map, capture, and eyedropper reserve the click for their indicated action."], ["Empty clone", "Source vectors must be below the clone in the same layer. Empty source stays transparent; defined calm still copies."], ["Divergence looks reversed", "Barbs point into incoming wind. Divergence bends the actual flow outward; convergence inward."], ["Object no longer in the project", "Undo or deletion can remove selection. Stale selections and inspector replies are now discarded. If an actual edit still fails, select the object's current row again."], ["Slow imported playback", "Wait for the readiness strip. Initial archive reads and evaluation can delay the requested steps/s."], ["Historical download failed", "Use Retry download beside the error. Check the requested period and connection if the archive remains unavailable."], ["Missing source / recent project", "Restore the referenced path, or use Open / Import to find it again. Missing project paths are removed from the recent list."], ["Beta expiration", "This beta expires on January 1st, 2027, according to the system date. Install an updated version to continue."]],
    related: ["layers", "clone", "divergence", "history", "export"] },
];

export function searchTopics(query: string): HelpTopic[] {
  const words = query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  return TOPICS.filter((topic) => {
    const text = JSON.stringify(topic).toLocaleLowerCase();
    return words.every((word) => text.includes(word));
  });
}
