export interface HelpTopic { id: string; title: string; paragraphs: string[]; steps?: string[]; image?: string; caption?: string }

/** Bundled instructions and screenshots: help is available without a connection. */
export const TOPICS: HelpTopic[] = [
  { id: "workspace", title: "Get started", image: "workspace", caption: "The map, layer stack, object inspector, and timeline.",
    paragraphs: ["VectorEffects builds animated wind and current fields from painted objects, imported GRIB files, and historical data. The map previews your work; GRIB export evaluates the project’s full grid.", "Create a project with the desired grid resolution, frame spacing, and number of frames. Save it as a .veproj file. File references and cached historical data must remain available when you reopen it."],
    steps: ["Choose New project on the start screen, or open an existing .veproj file.", "Select a layer, choose a tool, and draw on the map. Each completed gesture creates an object.", "Select an object to edit its properties in the inspector. Use Undo to reverse an edit.", "Save regularly. Crash recovery offers unsaved work on the start screen when available."] },
  { id: "tools", title: "Brushes, shapes, and erasing", image: "pixel-tools", caption: "A pixel brush keeps its screen proportions in Mercator, including at high latitudes.",
    paragraphs: ["Size in px means screen pixels at the moment you draw. Brushes and tool previews keep their proportions everywhere in the selected map projection. Size in km or nm means distance on the ground. Zooming later does not resize an existing object.", "The brush paints a swept circle or square. Circle stamps can fill a disc or a ring. Shape tools support dragged presets and free polygons. The curve tool follows an editable path.", "Target direction modes can use great-circle or rhumb-line bearings. Great circles take the shortest route; rhumb lines maintain a compass bearing. The angle offset turns the resulting direction. Circle stamps offer an angle from inward through tangent to outward.", "The eraser removes geometry from the active layer’s objects or data. It also cuts animated shapes: erased areas remain removed as the object’s perimeter changes. Use Undo to restore a cut."] },
  { id: "layers", title: "Layers and selection", image: "layers", caption: "Layer and object order, visibility, and speed thresholds.",
    paragraphs: ["Layers and objects are shown top first. Drag a layer header above or below another layer to change stacking order. Drag an object row within its layer to change its order, or onto another layer to move it there.", "Select the object you want to move, then drag it on the map. Only the selected objects appear in the moving preview. Shift-click extends the selection. Transform handles move, rotate, or scale the selection.", "Each layer has speed thresholds. Enable the filter and set its minimum and maximum. Values outside the inclusive range reveal the layers below. The filter applies after that layer’s painted objects and edits. Image thresholds use the displayed vector speed at each image position.", "The eye hides a layer. Lock a layer to prevent selecting or editing its objects. Wind and current layers remain separate field kinds during export."] },
  { id: "animation", title: "Keyframes and motion", image: "motion", caption: "Add constant motion from the Position track.",
    paragraphs: ["Expand an object in the timeline to see its animatable properties. Move the playhead to a frame, then click the diamond to add a key. Change the property or drag the object to edit its value. Once a property has keys, edits at other frames create keys.", "Click the graph toggle to inspect values over time. Keyframe easing controls the segment leaving that key. The object’s lifetime bar controls the frames in which it contributes.", "On the Position row, click →+ to add constant motion. Enter a true direction toward and a speed in your preferred units. Motion starts at the selected frame and ends at the next position key, or the object’s last frame. Existing keys in the interval require confirmation before replacement. One Undo restores the previous track.", "The separate ⇢ control adds the object’s own movement to the vector data it paints. It does not create a movement path. Unlink a followed position before setting an independent motion path.", "Playback speed is set beside the transport. The readiness strip shows which frames are prepared. Preparing imported data can take time; playback uses the cached frames once ready."] },
  { id: "shape", title: "Animate an object’s shape", image: "shape", caption: "Perimeter points appear only while shape-animation editing is enabled.",
    steps: ["Select a created or edited object, then click its shape-animation button in the timeline.", "Dots appear along the perimeter. Drag a dot to change its position at the selected frame.", "Visit another frame, add a shape key, and move the dots to create a changing outline.", "Click the same timeline button again, or select another tool, to leave shape-animation editing. The dots disappear.", "Use the eraser normally outside this mode. Its cuts remain destructive even on animated shapes."], paragraphs: ["Perimeter points keep their identity between keys so the outline can interpolate. Shape animation is stored with the object and supports Undo, save, and reopen."] },
  { id: "history", title: "Import historical data", image: "history", caption: "Choose wind or current archives and a time range.",
    paragraphs: ["Use the historical-data button in the layer panel to choose wind, currents, or both, and a UTC date range. Each archive becomes a layer. A longer range downloads more data.", "Progress appears in the bottom panel. If the download fails, click Retry download beside the error to repeat the same request. The error and retry action stay available while you move around the map.", "Imported GRIB and historical layers support speed thresholds, frame editing, and playback. A missing source file is reported in its layer; restore the file or import it again.", "Recent projects lists existing project files. Moved or deleted files disappear from the list; use Open to locate a project at its new location."] },
  { id: "macros", title: "Macros and missing frames", paragraphs: ["A macro records a region of animated vector data and can be placed as an object. Its properties and recorded movement follow the timeline.", "When a macro has fewer frames than the project, Interpolation strategy appears. Repeat Frames holds the most recent recorded frame and is the default. Empty Frames hides data between recorded frames. Interpolate blends u and v separately and interpolates recorded motion.", "Interpolation strategy applies to the whole macro and cannot be animated. Other available macro properties can be keyed normally."] },
  { id: "settings", title: "Units, arrows, and wind barbs", image: "settings", caption: "Separate arrow and wind-barb appearance controls.",
    paragraphs: ["Open Settings to choose km or nautical miles for distance, and knots, mph, or km/h for speed. The unit preference changes how values are entered and displayed; saved vector data remains in physical units.", "Arrows and wind barbs each have size, density, line width, color, opacity, speed fade, and drop-shadow controls. Preview each style in Settings, then adjust it for the map scale you use.", "Map projection changes how the earth is drawn. Pixel geometry remembers the projection used when it was created. Changing the view later does not change the exported geography."] },
  { id: "export", title: "Export GRIB2", image: "export", caption: "Choose output precision and the forecast reference time.",
    paragraphs: ["Choose Export GRIB, select the destination, reference date and time, and packing precision. Higher bit depth preserves more numeric precision and can increase file size. The displayed estimate is an upper bound; sparse fields can be much smaller.", "Export writes u and v separately for every project frame and each visible field kind. Uncovered cells are undefined, represented by GRIB bitmaps. A painted zero-speed cell is a defined calm value; it remains distinct from a missing cell.", "Image overlays are visual references and do not become wind or current values. The exported grid comes from the project resolution, independently of map zoom or screen size.", "This beta expires on January 1st, 2027, according to the system’s local date. Install the latest version before then to continue working."] },
];
