import { msg } from "../../i18n";
import type { Feature } from "../features";

/** The map: its tool palette, the view controls in the title bar, and the bars it draws itself. */
const features: Feature[] = [
  // The palette. Selecting a tool needs no reveal: every button is always on screen.
  { id: "tool:hand", label: msg("Hand"), description: msg("Pan the map, select objects and transform them."),
    keywords: [msg("pan"), msg("move"), msg("transform")], topic: "view" },
  { id: "tool:select", label: msg("Select"), description: msg("Draw a region of the map for tools to work within."),
    keywords: [msg("region"), msg("lasso"), msg("marquee")], topic: "selection" },
  { id: "tool:erase", label: msg("Erase"), description: msg("Erase geometry in the active layer."),
    keywords: [msg("eraser"), msg("delete"), msg("remove")], topic: "eraser" },
  { id: "tool:insert", label: msg("Insert macro"), description: msg("Place a captured run of frames back on the map."),
    keywords: [msg("macro"), msg("library"), msg("paste")], topic: "macros" },
  { id: "tool:capture", label: msg("Capture"), description: msg("Record a region of the field over a run of frames into the macro library."),
    keywords: [msg("record"), msg("macro"), msg("region")], topic: "capture" },
  { id: "tool:measure", label: msg("Measure"), description: msg("Measure distances and bearings on the map."),
    keywords: [msg("distance"), msg("bearing"), msg("ruler")], topic: "measure" },
  { id: "tool:brush", label: msg("Brush"), description: msg("Paint wind or current along a stroke."),
    keywords: [msg("paint"), msg("stroke"), msg("draw")], topic: "brush" },
  { id: "tool:circle", label: msg("Circle"), description: msg("Place circular flow around a point."),
    keywords: [msg("cyclone"), msg("vortex"), msg("ring")], topic: "circle" },
  { id: "tool:shape_fill", label: msg("Shape fill"), description: msg("Fill a polygon or preset shape with vectors or a gradient."),
    keywords: [msg("polygon"), msg("gradient"), msg("fill")], topic: "fill" },
  { id: "tool:mask", label: msg("Mask"), description: msg("Hide earlier data in the layer, revealing the layers below."),
    keywords: [msg("hide"), msg("cutout"), msg("transparency")], topic: "mask" },
  { id: "tool:clone_stamp", label: msg("Clone stamp"), description: msg("Copy vectors from one place in the layer to another."),
    keywords: [msg("copy"), msg("duplicate"), msg("clone")], topic: "clone" },
  { id: "tool:curve", label: msg("Curve"), description: msg("Paint a corridor of flow along a route, such as a jet or a channel."),
    keywords: [msg("path"), msg("jet"), msg("route")], topic: "path" },
  { id: "tool:intensity", label: msg("Intensify / reduce"), description: msg("Raise or lower the speed of the field below, keeping its direction."),
    keywords: [msg("strengthen"), msg("weaken"), msg("speed")], topic: "intensity" },
  { id: "tool:divergence", label: msg("Diverge / converge"), description: msg("Bend the flow away from or toward a centre."),
    keywords: [msg("divergence"), msg("convergence"), msg("spread")], topic: "divergence" },
  { id: "tool:turn", label: msg("Rotate flow"), description: msg("Turn the vectors below in place."),
    keywords: [msg("rotate"), msg("turn"), msg("veer")], topic: "rotation" },
  { id: "tool:warp", label: msg("Warp"), description: msg("Push or twist features of the field."),
    keywords: [msg("push"), msg("twist"), msg("distort")], topic: "warp" },
  { id: "tool:liquify", label: msg("Displace"), description: msg("Select an area of the field and move it somewhere else."),
    keywords: [msg("move"), msg("shift"), msg("relocate")], topic: "warp" },

  // The select and capture bars.
  { id: "select:shape", label: msg("Region shape"), description: msg("Draw the region as a rectangle, a circle or a lasso."),
    keywords: [msg("rectangle"), msg("lasso"), msg("circle")], topic: "selection", reveal: ["tool:select"] },
  { id: "select:deselect", label: msg("Deselect"), description: msg("Clear the selected region."),
    keywords: [msg("clear selection"), msg("select none")], topic: "selection", reveal: ["tool:select"] },
  { id: "capture:shape", label: msg("Capture region shape"), description: msg("Draw the region to record as a rectangle, a circle or a lasso."),
    keywords: [msg("rectangle"), msg("lasso"), msg("circle")], topic: "capture", reveal: ["tool:capture"] },
  { id: "capture:movement", label: msg("Record movement"), description: msg("Keep the region's movement between frames in the macro."),
    keywords: [msg("motion"), msg("static"), msg("follow")], topic: "capture", reveal: ["tool:capture"] },
  { id: "capture:start", label: msg("Start capture"), description: msg("Start recording the region into a macro."),
    keywords: [msg("record"), msg("macro")], topic: "capture", reveal: ["tool:capture"] },

  // The eraser and insert bars.
  { id: "erase:size", label: msg("Eraser size"), description: msg("How large the eraser is, on screen or on the ground."),
    keywords: [msg("diameter"), msg("width")], topic: "eraser", reveal: ["tool:erase"] },
  { id: "erase:shape", label: msg("Eraser shape"), description: msg("Erase with a circle or a square."),
    keywords: [msg("square"), msg("circle")], topic: "eraser", reveal: ["tool:erase"] },
  { id: "erase:feather", label: msg("Eraser feather"), description: msg("How soft the eraser's edge is."),
    keywords: [msg("soft edge"), msg("blur")], topic: "eraser", reveal: ["tool:erase"] },
  { id: "insert:macro", label: msg("Macro to insert"), description: msg("Choose which macro from the library to place."),
    keywords: [msg("library"), msg("macro")], topic: "macros", reveal: ["tool:insert"] },
  { id: "insert:refresh", label: msg("Refresh macro library"), description: msg("Re-read the macro library from disk."),
    keywords: [msg("reload"), msg("library")], topic: "macros", reveal: ["tool:insert"] },

  // The measure bar.
  { id: "measure:dividers", label: msg("Dividers"), description: msg("Measure a chain of legs, with the distance and bearing of each."),
    keywords: [msg("distance"), msg("legs"), msg("waypoints")], topic: "dividers", reveal: ["measure:dividers"] },
  { id: "measure:passage", label: msg("Great circle / rhumb"), description: msg("Compare the great-circle and rhumb-line routes between two points."),
    keywords: [msg("great circle"), msg("rhumb line"), msg("route")], topic: "measure", reveal: ["measure:passage"] },
  { id: "measure:rings", label: msg("Range rings"), description: msg("Draw rings of equal ground distance around a centre."),
    keywords: [msg("radius"), msg("distance"), msg("circles")], topic: "rings", reveal: ["measure:rings"] },
  { id: "measure:interval", label: msg("Ring interval"), description: msg("The spacing between range rings."),
    keywords: [msg("spacing"), msg("distance")], topic: "rings", reveal: ["measure:rings"] },
  { id: "measure:ring-count", label: msg("Number of rings"), description: msg("How many range rings to draw."),
    keywords: [msg("rings"), msg("count")], topic: "rings", reveal: ["measure:rings"] },
  { id: "measure:clear-all", label: msg("Clear all measurements"), description: msg("Remove every measurement from the map."),
    keywords: [msg("delete"), msg("remove")], topic: "measure", reveal: ["tool:measure"] },

  // The view controls in the title bar.
  { id: "map:undo", label: msg("Undo"), description: msg("Undo the last change."),
    keywords: [msg("revert")], topic: "troubleshooting" },
  { id: "map:redo", label: msg("Redo"), description: msg("Redo the change last undone."),
    keywords: [msg("repeat")], topic: "troubleshooting" },
  { id: "map:glyphs", label: msg("Glyphs"), description: msg("Show direction glyphs: wind as barbs, currents as arrows."),
    keywords: [msg("wind barbs"), msg("arrows"), msg("symbols")], topic: "settings" },
  { id: "map:graticule", label: msg("Graticule"), description: msg("Show lines of latitude and longitude."),
    keywords: [msg("grid"), msg("latitude"), msg("longitude")], topic: "view" },
  { id: "map:auto-scale", label: msg("Auto scale"), description: msg("Stretch the colour ramp across the speeds in view."),
    keywords: [msg("colour scale"), msg("colour ramp"), msg("range")], topic: "view" },
  { id: "map:charts", label: msg("Charts"), description: msg("Draw electronic nautical charts (S-57) under the map."),
    keywords: [msg("nautical chart"), msg("ENC"), msg("backdrop")], topic: "view" },
  { id: "map:osm", label: msg("OpenStreetMap"), description: msg("Use OpenStreetMap tiles in place of the built-in basemap."),
    keywords: [msg("basemap"), msg("tiles"), msg("streets")], topic: "view" },
  { id: "map:readout", label: msg("Readout"), description: msg("Show the position and field under the pointer."),
    keywords: [msg("cursor"), msg("coordinates"), msg("position")], topic: "view" },
  { id: "map:legend", label: msg("Legend"), description: msg("Show the colour legend with the speeds at its ends."),
    keywords: [msg("colour scale"), msg("colour ramp")], topic: "view" },
];
export default features;
